[package]
name = "creativity-game"
default-run = "creativity-game"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]
members = ["xtask"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
# bevy
bevy = "0.12"
bevy_mod_picking = "0.17"
# generic

# hanabi particles
[dependencies.bevy_hanabi]
version = "0.8"
default-features = false
features = ["3d"]

# bevy_replicon
[dependencies.bevy_replicon]
git = "https://github.com/Bendzae/bevy_replicon_fork.git"
branch = "bevy-0.12"