[toolchain]
channel = "1.73"
# channel = "nightly-2023-10-18"
# channel = "nightly"
# components = ["cargo", "rustc", "clippy", "rust-std", "rustfmt"]
# profile = "complete"
# targets = [
# 	"x86_64-pc-windows-gnu",
# 	"x86_64-apple-darwin",
# 	"aarch64-apple-darwin",
# ]
