[alias]
xtask = "run -p xtask --"
rs = "r -- server"
rc = "r -- client"
rrs = "r --no-default-features --features dev,editor -- server"
rrc = "r --no-default-features --features dev,editor -- client"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"